name: Swagger

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ReDoc CLI
        run: npm install -g redoc-cli  # Instalacja ReDoc CLI

      - name: Generate ReDoc
        run: redoc-cli bundle -o ./index.html ./api.json  # Generowanie dokumentacji ReDoc z pliku specyfikacji API

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
